server:
  port: 8085

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          # Apunta al JWKS de tu realm de Keycloak (ajusta host/puerto/realm)
          jwk-set-uri: http://localhost:8080/realms/tfm-bandas/protocol/openid-connect/certs

#  cloud:
#    gateway:
#      server:
#        webflux:
#          default-filters:
#            # Añadiremos filtros propios en el siguiente paso
#                    - RemoveRequestHeader=Cookie
#          routes:
#            - id: users
#              uri: http://localhost:8081
#              predicates:
#                - Path=/api/users/**
#                - Path=/api/instruments/**
#
#            - id: events
#              uri: http://localhost:8083
#              predicates:
#                - Path=/api/events/**
#
#            - id: scores
#              uri: http://localhost:8082
#              predicates:
#                - Path=/api/scores/**
#
#            - id: surveys
#              uri: http://localhost:8084
#              predicates:
#                - Path=/api/surveys/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.tfm.bandas.gateway: DEBUG
    org.springframework.security: DEBUG

gateway:
  instruments:
    path: /api/instruments/**
  roles:
    path: /api/roles/**
  users:
    uri: http://localhost:8081
    path: /api/users/**
  events:
    uri: http://localhost:8083
    path: /api/events/**
  scores:
    uri: http://localhost:8082
    path: api/scores/**
  surveys:
    uri: http://localhost:8084
    path: /api/surveys/**
